# .github/workflows/main-cicd.yml

name: Main CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build Spring Boot JAR
        run: |
          cd FineApple # 실제 스프링 프로젝트 폴더 이름으로 수정
          ./mvnw clean package -DskipTests
          cd ..

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker images
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-spring-dev ./FineApple # 실제 스프링 프로젝트 폴더 이름으로 수정
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-fastapi-dev ./fastapi-server
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-batch-dev ./batch

          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-spring-dev
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-fastapi-dev
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/fineapple-batch-dev

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "--- Navigating to project directory ---"
            cd ~/fineapple-service
            
            echo "--- Pulling latest images from Docker Hub ---"
            docker compose pull
            
            echo "--- Shutting down existing containers ---"
            docker compose down
            
            echo "--- Starting new containers in detached mode ---"
            docker compose up -d
            
            echo "--- Waiting for containers to stabilize (10 seconds) ---"
            sleep 10
            
            echo "--- Current status of all containers ---"
            docker compose ps -a
            
            echo "--- Displaying last 50 lines of logs ---"
            docker compose logs --tail=50
